version: '3'

services:
  postgres:
    image: "hwsc/hwsc-user-svc-psql:test-int"
    container_name: "test-postgres"
    ports:
      - "${hosts_postgres_port}:${hosts_postgres_port}"
  user-svc:
    image: "hwsc/hwsc-user-svc:int"
    container_name: "test-user-svc"
    ports:
      - "${hosts_user_port}:${hosts_user_port}"
    environment:
      - hosts_user_address
      - hosts_user_port
      - hosts_user_network
      - hosts_postgres_host=postgres
      - hosts_postgres_db
      - hosts_postgres_user
      - hosts_postgres_password
      - hosts_postgres_sslmode
      - hosts_postgres_port
      - hosts_smtp_host
      - hosts_smtp_port
      - hosts_smtp_username
      - hosts_smtp_password
